package com.cdp.myapiretrofit.clases

data class Detalles (
    var index_id : Int,
    var orden_trabajo: String,
    var estado_chasis: String,
    var estado_cubiertas: String,
    var pintura: String,
    var golpes: String,
    var tornillos: String,
    var asientos: String,
    var estado_motores: String,
    var estado_escobillas: String,
    var nivel_aceite_transm : String,
    var estado_transmision: String,
    var fugas: String,
    var estado_de_frenos: String,
    var estado_de_bandas: String,
    var funcionamiento : String,
    var nivel_de_liquido: String,
    var ajuste_de_frenos : String,
    var prueba_de_frenado : String,
    var estado_del_motor: String,
    var estado_cadena: String,
    var estado_piston: String,
    var nivel_de_aceite: String,
    var lubricacion: String,
    var escobillas: String,
    var eje_de_direccion: String,
    var funcionamiento1: String,
    var fusibles: String,
    var controladores: String,
    var estado_de_cables : String,
    var funcionamiento2: String,
    var indicador_o_display: String,
    var multipiloto_o_joystick: String,
    var estado_contactos: String,
    var contactor : String,
    var otros: String,
    var fugas1 : String,
    var estado_mangueras : String,
    var estado_poleas: String,
    var enlogacion_cadenas: String,
    var estado_cilindros: String,
    var bloque_valvulas: String,
    var funcionamiento3: String,
    var piezas_deslizantes: String,
    var lubricacion_espejo: String,
    var estados_horquillas: String,
    var estado_de_filtros: String,
    var fugas2: String,
    var nivel_de_aceite1 : String,
    var tanque_o_deposito: String,
    var funcionamiento4: String,
    var motor_de_elevacion: String,
    var escobillas1: String,
    var estado_interconectores : String,

    var estado_tornillos: String,
    var voltaje : String,
    var caida_de_voltaje : String,
    var cubiertas: String,
    var postes: String,
    var sulfatacion: String,
    var nivel_electrolito: String,
    var exploradoras: String,
    var luz_giratoria: String,
    var cinturon: String,

    var extintor: String,
    var cargador: String,
    var rueda_motriz: String,
    var ruedas_de_apoyo : String,
    var ruedas_de_direccion: String,
    var ruedas_de_carga: String
    )